unique_ids:
  forms:
    Form1: '1722304730373792494495993.0189'
    Form1.ItemTemplate1: '172291127757062526468510.59951'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: 6ERVMUPP2OXOF7UNNZOVEZCHDABU5COO
    theme.css: 5WEHL7RAMJAEIETP2GKK2YRFRR4VVLAU
  scripts: {}
