color_scheme:
  colors:
  - {color: '#D9D9D9', name: Bone White}
  - {color: '#363732', name: Olive black}
  - {color: '#296EB4', name: Blue}
  - {color: '#ffffff', name: White}
  - {color: '#000000', name: Black}
  preset_groups: []
roles:
- {name: '.nav-button {     cursor: pointer;     transition: transform 0.3s ease-in-out;'}
- {name: '.nav-button.active {     transform: rotate(90deg);'}
- {name: '.dropdown-menu {     display: none;'}
- {name: '.nav-button.active + .dropdown-menu {     display: block;'}
