roles: []
color_scheme:
  colors:
  - {name: Bone White, color: '#D9D9D9'}
  - {name: Olive black, color: '#363732'}
  - {name: Blue, color: '#296EB4'}
  - {name: Black, color: '#000000'}
  - {name: White, color: '#FFFFFF'}
  preset_groups: []
